Make math.round in gaussian delay no longer shadowed
Fixes

  File "/cbc-casper/simulations/network_delay.py", line 31, in gaussian_delay
    return round(random.gauss(MU, SIGMA))
TypeError: 'int' object is not callable